# Generated by Django 4.1 on 2022-09-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notes_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=60)),
                ('firstName', models.CharField(max_length=60)),
                ('lastName', models.CharField(max_length=60)),
                ('phoneNumber', models.CharField(max_length=12)),
                ('images', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
