# Generated by Django 4.1 on 2022-09-02 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='images',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
