# Generated by Django 4.1 on 2022-09-02 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='images',
            new_name='file',
        ),
    ]
