# Generated by Django 4.1 on 2022-09-02 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_images_user_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='file',
            new_name='Images',
        ),
    ]
