# Generated by Django 4.1 on 2022-09-02 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_file_user_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Images',
        ),
    ]
